name: RPMagic
main: com.github.boltydawg.Main
version: 0.5
author: BoltyDawg
description: A magical class-based roleplaying system!
depend: [Magic,ArmorEquipEvent]
commands:
  getbook:
    description: Gives the sender a spell book
    usage: /getbook <spell>
    permission: rpm.isMage
    permission-message: You don't have the rpm.isMage permission.
  getwand:
    description: Give a player his/her wand
    usage: /getwand <player>
    permission: rpm.getwand
    permission-message: You don't have the rpm.getwand permission.
  setmagic:
    description: Set the value of a player's Magicka
    usage: /setmagic <player> <value>
    permission: rpm.setmagic
    permission-message: You don't have the rpm.setmagic permission.
  rpmcast:
    description: Cast a spell
    usage: /rpmcast <spell>
    permission: rpm.isMage
    permission-message: You don't have the rpm.isMage permission.
  teach:
    description: teach a player a spell
    usage: /teach <player> <spell>
    permission: rpm.isMage
    permission-message: You don't have the rpm.isMage permission.
  rpmage:
    description: create or clear a mage's records
    usage: /rpmage <create/delete> <player>
    permission: rpm.rpmage
    permission-message: You don't have the rpm.rpmage permission.
  setclass:
    description: set a player's class
    usage: /setclass <player> <class>
    permission: rpm.setclass
    permission-message: You don't have the rpm.setclass permission.
  setsubclass:
    description: set a player's subclass
    usage: /setclass <player> <subclass>
    permission: rpm.setsubclass
    permission-message: You don't have the rpm.setsubclass permission.
  r:
    description: Let someone know that you will remember this.
    usage: /r
    permission: rpm.r
    permission-message: You don't have the rpm.r permission.
    