name: RPMagic
main: com.github.boltydawg.Main
version: 0.5
author: BoltyDawg
description: A magical class-based roleplaying system!
depend: [Magic]
commands:
  getbook:
    description: Gives the sender a spell book
    usage: /getbook <spell>
    permission: rpm.mages
    permission-message: You don't have the rpm.mages permission. 
  getwand:
    description: Give a player his/her wand
    usage: /getwand <player>
    permission: rpm.getwand
    permission-message: You don't have the rpm.getwand permission.
  rpcast:
    description: Cast a spell
    usage: /rpcast <spell>
    permission: rpm.mages
    permission-message: You don't have the rpm.mages permission.
  teach:
    description: Teach a Mage a spell
    usage: /teach <player> <spell>
    permission: rpm.mages
    permission-message: You don't have the rpm.mages permission.
  rpmage:
    description: Manually create or clear a Mage's records
    usage: /rpmage <create/delete> <player>
    permission: rpm.rpmage
    permission-message: You don't have the rpm.rpmage permission.
  r:
    description: Let someone know that you will remember this.
    usage: /r
    permission: rpm.remember
    permission-message: You don't have the rpm.remember permission.
  start:
    description: Start a new character
    usage: /start <class> <name of your character, including spaces>
    permission: rpm.start
    permission-message: You don't have the rpm.start permission.
    
  setclass:
    description: set a player's class
    usage: /setclass <player> <class>
    permission: rpm.setclass
    permission-message: You don't have the rpm.setclass permission.
  setsubclass:
    description: set a player's subclass
    usage: /setsubclass <player> <subclass>
    permission: rpm.setsubclass
    permission-message: You don't have the rpm.setsubclass permission.
  setmagic:
    description: Set the value of a player's Magicka
    usage: /setmagic <player> <value>
    permission: rpm.setmagic
    permission-message: You don't have the rpm.setmagic permission.