name: RPMagic
main: com.github.boltydawg.Main
version: 1.2
author: BoltyDawg
description: A magical class-based roleplaying system!
depend: [Magic]
api-version: 1.13
commands:
  getbook:
    description: Gives the sender a spell book
    usage: /getbook <spell>
    permission: rpm.mages
    permission-message: You don't have the rpm.mages permission. 
  getwand:
    description: Give a player his/her wand
    usage: /getwand <player>
    permission: rpm.admin
    permission-message: You don't have the rpm.admin permission.
  rpcast:
    description: Cast a spell
    usage: /rpcast <spell>
    permission: rpm.mages
    permission-message: You don't have the rpm.mages permission.
  teach:
    description: Teach a Mage a spell
    usage: /teach <player> <spell>
    permission: rpm.admin
    permission-message: You don't have the rpm.admin permission.
  r:
    description: Let someone know that you will remember this.
    usage: /r
    permission: rpm.default
    permission-message: You don't have the rpm.default permission.
  start:
    description: Start a new character
    usage: /start <class> <name of your character, including spaces>
    permission: rpm.default
    permission-message: You don't have the rpm.default permission. 
  dropxp:
    description: Drops the desired amount of XP, or all
    usage: /dropxp <amount, or all>
    permission: rpm.default
    permission-message: You don't have the rpm.default permission.
  forget:
    description: Forget a spell
    usage: /forget <name of spell, in lowercase>
    permission: rpm.mages
    permission-message: You don't have the rpm.mages permission. 
  subclass:
    description: set a player's subclass
    usage: /subclass <player> <subclass>
    permission: rpm.admin
    permission-message: You don't have the rpm.admin permission.
  spellinfo:
    description: Get the details of a certain spell
    usage: /spellinfo <spell name>
    permission: rpm.mages
    permission-message: You don't have the rpm.mages permission.
  getkey:
    description: Gives you the key to all of your chests
    usage: /getkey
    permission: rpm.default
    permission-message: You don't have the rpm.default permission.
  role:
    description: set a player's role
    usage: /subclass <player> <role>
    permission: rpm.admin
    permission-message: You don't have the rpm.admin permission.
  local:
    description: toggle local chat
    usage: /local
    permission: rpm.admin
    permission-message: You don't have the rpm.admin permission.
  openinv:
    description: Open a players inventory
    usage: /openinv <player>
    permission: rpm.admin
    permission-message: You don't have the rpm.admin permission.
  dungeons:
    description: Options for starting, ending, and resetting dungeons
    usage: /dungeons <start> <dungeon name> | <end> <dungeon name> | <reset>
    permission: rpm.admin
    permission-message: You don't have the rpm.admin permission.
  rename:
    description: Rename the item in your main hand.
    usage: /rename <new item name, including any spaces>
    permission: rpm.default
    permission-message: You don't have the rpm.default permission.